# This is a basic workflow for testing Monkeypatch

name: tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tests"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - run: git branch
      - run: bash
      - run: bash install.sh
      - run: |
           echo "$HOME/.mon/src/" >> $GITHUB_PATH
           echo "$HOME/.mon/registered/bin" >> $GITHUB_PATH
      - run: bash tests.sh
